#OBJS specifies which files to compile as part of the project
OBJS = *.c

#OBJ_NAME specifies the name of our exectuable
OBJ_NAME = game.exe

#This is the target that compiles our executable
all : $(OBJS)
	gcc $(OBJS) -IC:\mingw_dev_lib\include\SDL2 -LC:\mingw_dev_lib\lib -g -Wall -m32 -lmingw32 -lSDL2main -lSDL2 -o $(OBJ_NAME)
